### ISSUE TITLE
Gamemode suggestions - and a bug I have found

### ISSUE THREAD

**Issue by GeorgeVincent** [alkarinv/ArenaCTF#1]
Hi, first off everyone on my server loves this plugin, however there is one thing I would suggest for improvement: multiple gamemodes. Instead of JUST capturing the enemy's flag what about One Flag, where one team would defend their own flag for 5 minutes and if the enemy score it they keep defending and after the 5 minutes the team swaps, so the team defending first have to try and beat the other teams score, r.g Team red defends first, in the 5 minutes blue team score the flag twice, then the teams swap and team red need to beat 2 to win if they score 0 or 1 then they lose, and then for a tie break one round of neutral flag (one neutral flag on the map and both teams fight to capture it. Neutral flag could be a gamemode in itself, winning after 2 out of 3 or 3 out of 5.

The bug I found is that if you p[lay one round using /ctf auto when you play the next round certain players can't capture the flag, for example, if I got the other teams flag and when I cap it at my base it tells me I have picked up the enemy's flag again, also in a second game multiple flags per flag point spawn

Thanks for reading this :)

**Comment by alkarinv** [comment]
Thanks man!

I'll look into those bugs when i can.. probably during the week unfortunately as its the end of school for me, super busy time.

I like the new gamemode.. i'll see what I can do!

**Comment by alkarinv** [comment]
Can you try this version.

http://dev.bukkit.org/media/files/656/414/ArenaCTF.jar

I think this problem is now fixed.  Sorry about the wait, it's finals time during school.
