### ISSUE TITLE
CTF start problem

### ISSUE THREAD

**Issue by Gamerturk** [alkarinv/ArenaCTF#3]
12:24:57 [SEVERE] java.lang.NoSuchMethodException: mc.alk.ctf.FlagVictory.<init>
(mc.alk.arena.competition.match.Match)
12:24:57 [SEVERE]       at java.lang.Class.getConstructor0(Unknown Source)
12:24:57 [SEVERE]       at java.lang.Class.getConstructor(Unknown Source)
12:24:57 [SEVERE]       at mc.alk.arena.objects.victoryconditions.VictoryType.cr
eateVictoryCondition(VictoryType.java:66)
12:24:57 [SEVERE]       at mc.alk.arena.competition.match.Match.addVictoryCondit
ions(Match.java:756)
12:24:57 [SEVERE]       at mc.alk.arena.competition.match.Match.<init>(Match.jav
a:153)
12:24:57 [SEVERE]       at mc.alk.arena.competition.match.ArenaMatch.<init>(Aren
aMatch.java:72)
12:24:57 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.getMatchA
ndRemove(ArenaMatchQueue.java:417)
12:24:57 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch
(ArenaMatchQueue.java:398)
12:24:57 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch
(ArenaMatchQueue.java:299)
12:24:57 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfN
eeded(ArenaMatchQueue.java:194)
12:24:57 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.addToQueu
e(ArenaMatchQueue.java:118)
12:24:57 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.add(Arena
MatchQueue.java:88)
12:24:57 [SEVERE]       at mc.alk.arena.controllers.BattleArenaController.addToQ
ue(BattleArenaController.java:217)
12:24:57 [SEVERE]       at mc.alk.arena.executors.BAExecutor.join(BAExecutor.jav
a:231)
12:24:57 [SEVERE]       at mc.alk.arena.executors.BAExecutor.join(BAExecutor.jav
a:146)
12:24:57 [SEVERE]       at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown
 Source)
12:24:57 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
12:24:57 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
12:24:57 [SEVERE]       at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExe
cutor.java:239)
12:24:57 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
12:24:57 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:186)
12:24:57 [SEVERE]       at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCo
mmand(CraftServer.java:514)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:980)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.chat(Pl
ayerConnection.java:898)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.a(Playe
rConnection.java:853)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packe
t3Chat.java:44)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.NetworkManager.b(Network
Manager.java:290)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.d(Playe
rConnection.java:113)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.ServerConnection.b(Sourc
eFile:39)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.DedicatedServerConnectio
n.b(SourceFile:30)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.r(Minecr
aftServer.java:598)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.DedicatedServer.r(Dedica
tedServer.java:224)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.q(Minecr
aftServer.java:494)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.run(Mine
craftServer.java:427)
12:24:57 [SEVERE]       at net.minecraft.server.v1_4_R1.ThreadServerApplication.
run(SourceFile:849)
12:24:57 [SEVERE] [BA Error] [BattleArena v3.7.9.9.8]:public boolean mc.alk.aren
a.executors.BAExecutor.join(mc.alk.arena.objects.ArenaPlayer,mc.alk.arena.object
s.MatchParams,java.lang.String[]) : mc.alk.arena.executors.BAExecutor@90004  : m
c.alk.arena.executors.BaseExecutor$Arguments@18a14c7
12:24:57 [SEVERE] [BA Error] object=mc.alk.arena.objects.ArenaPlayer@859b4236
12:24:57 [SEVERE] [BA Error] object=CaptureTheFlag:ctf:CaptureTheFlag rating=RAT
ED,nteams=2,teamSize=1,vc=FLAGVICTORY
12:24:57 [SEVERE] [BA Error] object=[Ljava.lang.String;@5a21ea
12:24:57 [SEVERE] [BA Error] Cause=java.lang.NullPointerException
12:24:57 [SEVERE] java.lang.NullPointerException
12:24:58 [SEVERE]       at mc.alk.arena.controllers.MethodController.addAllEvent
s(MethodController.java:333)
12:24:58 [SEVERE]       at mc.alk.arena.controllers.MethodController.addListener
(MethodController.java:325)
12:24:58 [SEVERE]       at mc.alk.arena.competition.Competition.addArenaListener
(Competition.java:161)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.Match.addVictoryCondit
ion(Match.java:785)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.Match.addVictoryCondit
ions(Match.java:776)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.Match.<init>(Match.jav
a:153)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.ArenaMatch.<init>(Aren
aMatch.java:72)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.getMatchA
ndRemove(ArenaMatchQueue.java:417)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch
(ArenaMatchQueue.java:398)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch
(ArenaMatchQueue.java:299)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfN
eeded(ArenaMatchQueue.java:194)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.addToQueu
e(ArenaMatchQueue.java:118)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.add(Arena
MatchQueue.java:88)
12:24:58 [SEVERE]       at mc.alk.arena.controllers.BattleArenaController.addToQ
ue(BattleArenaController.java:217)
12:24:58 [SEVERE]       at mc.alk.arena.executors.BAExecutor.join(BAExecutor.jav
a:231)
12:24:58 [SEVERE]       at mc.alk.arena.executors.BAExecutor.join(BAExecutor.jav
a:146)
12:24:58 [SEVERE]       at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown
 Source)
12:24:58 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
12:24:58 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
12:24:58 [SEVERE]       at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExe
cutor.java:239)
12:24:58 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
12:24:58 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:186)
12:24:58 [SEVERE]       at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCo
mmand(CraftServer.java:514)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:980)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.chat(Pl
ayerConnection.java:898)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.a(Playe
rConnection.java:853)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packe
t3Chat.java:44)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.NetworkManager.b(Network
Manager.java:290)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.d(Playe
rConnection.java:113)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.ServerConnection.b(Sourc
eFile:39)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.DedicatedServerConnectio
n.b(SourceFile:30)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.r(Minecr
aftServer.java:598)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.DedicatedServer.r(Dedica
tedServer.java:224)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.q(Minecr
aftServer.java:494)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.run(Mine
craftServer.java:427)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.ThreadServerApplication.
run(SourceFile:849)
12:24:58 [SEVERE] [BA Error] Trace Continued
12:24:58 [SEVERE] java.lang.reflect.InvocationTargetException
12:24:58 [SEVERE]       at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown
 Source)
12:24:58 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
12:24:58 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
12:24:58 [SEVERE]       at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExe
cutor.java:239)
12:24:58 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
12:24:58 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:186)
12:24:58 [SEVERE]       at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCo
mmand(CraftServer.java:514)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:980)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.chat(Pl
ayerConnection.java:898)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.a(Playe
rConnection.java:853)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packe
t3Chat.java:44)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.NetworkManager.b(Network
Manager.java:290)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.PlayerConnection.d(Playe
rConnection.java:113)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.ServerConnection.b(Sourc
eFile:39)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.DedicatedServerConnectio
n.b(SourceFile:30)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.r(Minecr
aftServer.java:598)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.DedicatedServer.r(Dedica
tedServer.java:224)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.q(Minecr
aftServer.java:494)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.MinecraftServer.run(Mine
craftServer.java:427)
12:24:58 [SEVERE]       at net.minecraft.server.v1_4_R1.ThreadServerApplication.
run(SourceFile:849)
12:24:58 [SEVERE] Caused by: java.lang.NullPointerException
12:24:58 [SEVERE]       at mc.alk.arena.controllers.MethodController.addAllEvent
s(MethodController.java:333)
12:24:58 [SEVERE]       at mc.alk.arena.controllers.MethodController.addListener
(MethodController.java:325)
12:24:58 [SEVERE]       at mc.alk.arena.competition.Competition.addArenaListener
(Competition.java:161)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.Match.addVictoryCondit
ion(Match.java:785)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.Match.addVictoryCondit
ions(Match.java:776)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.Match.<init>(Match.jav
a:153)
12:24:58 [SEVERE]       at mc.alk.arena.competition.match.ArenaMatch.<init>(Aren
aMatch.java:72)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.getMatchA
ndRemove(ArenaMatchQueue.java:417)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch
(ArenaMatchQueue.java:398)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch
(ArenaMatchQueue.java:299)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfN
eeded(ArenaMatchQueue.java:194)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.addToQueu
e(ArenaMatchQueue.java:118)
12:24:58 [SEVERE]       at mc.alk.arena.objects.queues.ArenaMatchQueue.add(Arena
MatchQueue.java:88)
12:24:58 [SEVERE]       at mc.alk.arena.controllers.BattleArenaController.addToQ
ue(BattleArenaController.java:217)
12:24:58 [SEVERE]       at mc.alk.arena.executors.BAExecutor.join(BAExecutor.jav
a:231)
12:24:58 [SEVERE]       at mc.alk.arena.executors.BAExecutor.join(BAExecutor.jav
a:146)
12:24:58 [SEVERE]       ... 20 more

What am i doing wrong? i set 2 team spawns and flags and waitrooms.Why victory condition get error?

**Comment by Gamerturk** [comment]
The error is solved.i delete victory condition in capturetheflagconfig.yml

**Comment by alkarinv** [comment]
Sorry about that, glad its fixed!
