### ISSUE TITLE
Auto Start?

### ISSUE THREAD

**Issue by FarmerKaine** [alkarinv/ArenaCTF#5]
It's not allowing me to throw the command /ctf auto like all the other arenas...

Am I missing something?

I have an arena created, I can /ctf join, have a few other people do the same...  the match works fine...  but I have no messages that says it's starting soon, and no "auto" switch...

What am I missing in this whole thing?

FarmerKaine

**Comment by alkarinv** [comment]
Sorry, so i changed the default from a JoinPhase to a queue.

To change it back to a JoinPhase (which you have to open to join)

{{{
CaptureTheFlag:
    joinType: JoinPhase
}}}

**Comment by alkarinv** [comment]
Also did you have to make an account to post this error?  I kind of want people to be able to post errors without that.

**Comment by FarmerKaine** [comment]
Yes, I made an account...  but I should have weeks ago...  I have a ton of
questions!
